// pdf-form-fields.ts
export const PDF_FIELD_MAP = {
    // Basic Info
    characterName: '1 LAST NAME FIRST NAME MIDDLE INITIAL',
    profession: '2 PROFESSION RANK IF APPLICABLE',
    employer: '3 EMPLOYER',
    nationality: '4 NATIONALITY',
    genderMale: 'Check Box8',
    genderFemale: 'Check Box7',
    ageAndDob: '6 AGE AND DOB',
    educationAndOccupation: '7 EDUCATION AND OCCUPATION',
    physicalDescription: '10 PHYSICAL DESCRIPTION',

    // Adaptation Checkboxes
    adaptedToViolence1: 'Check Box1',
    adaptedToViolence2: 'Check Box2',
    adaptedToViolence3: 'Check Box3',
    adaptedToHelplessness1: 'Check Box4',
    adaptedToHelplessness2: 'Check Box5',
    adaptedToHelplessness3: 'Check Box6',

    // Attributes
    strScore: 'STR',
    strPercent: 'STRx5',
    strDistinguishingFeatures: 'STR DISTINGUISING FEATURES',
    conScore: 'CON',
    conPercent: 'CONx5',
    conDistinguishingFeatures: 'CON DISTINGUISING FEATURES',
    dexScore: 'DEX',
    dexPercent: 'DEXx5',
    dexDistinguishingFeatures: 'DEX DISTINGUISING FEATURES',
    intScore: 'INT',
    intPercent: 'INTx5',
    intDistinguishingFeatures: 'INT DISTINGUISING FEATURES',
    powScore: 'POW',
    powPercent: 'POWx5',
    powDistinguishingFeatures: 'POW DISTINGUISING FEATURES',
    chaScore: 'CHA',
    chaPercent: 'CHAx5',
    chaDistinguishingFeatures: 'CHA DISTINGUISING FEATURES',

    // Bonds
    bond1Type: 'BOND 1',
    bond1Score: 'BOND 1 SCORE',
    bond2Type: 'BOND 2',
    bond2Score: 'BOND 2 SCORE',
    bond3Type: 'BOND 3',
    bond3Score: 'BOND 3 SCORE',
    bond4Type: 'BOND 4',
    bond4Score: 'BOND 4 SCORE',
    bond5Type: 'BOND 5',
    bond5Score: 'BOND 5 SCORE',
    bond6Type: 'BOND 6',
    bond6Score: 'BOND 6 SCORE',

    // Derived Stats
    maxHp: 'MAXIMUMHit Points HP', 
    maxWp: 'MAXIMUMWillpower Points WP', 
    maxSan: 'MAXIMUMSanity Points SAN', 
    currentBp: 'CURRENTBreaking Point BP',
    
    // Portrait
    portrait: 'Portrait',
    
    // Skills
    'Accounting': 'Accounting 10',
    'Alertness': 'Alertness 20',
    'Anthropology': 'Anthropology 0',
    'Archaeology': 'Archeology 0',
    'Art': 'Art 0',
    'Art_specializations': 'Art',
    'Artillery': 'Artillery 0',
    'Athletics': 'Athletics 30',
    'Bureaucracy': 'Bureaucracy 10',
    'Computer Science': 'Computer Science 0',
    'Craft': 'Craft 0',
    'Craft_specializations': 'Craft',
    'Criminology': 'Criminology 10',
    'Demolitions': 'Demolitions 0',
    'Disguise': 'Disguise 10',
    'Dodge': 'Dodge 30',
    'Drive': 'Drive 20',
    'Firearms': 'Firearms 20',
    'First Aid': 'First Aid 10',
    'Forensics': 'Forensics 0',
    'Heavy Machinery': 'Heavy Machinery 10',
    'Heavy Weapons': 'Heavy Weapons 0',
    'History': 'History 10',
    'HUMINT': 'HUMINT 10',
    'Law': 'Law 0',
    'Medicine': 'Medicine 0',
    'Melee Weapons': 'Melee Weapons 30',
    'Military Science': 'Military Science 0',
    'Military Science_specializations': 'Military Science',
    'Navigate': 'Navigate 10',
    'Occult': 'Occult 10',
    'Persuade': 'Persuade 20',
    'Pharmacy': 'Pharmacy 0',
    'Pilot': 'Pilot 0',
    'Pilot_specializations': 'Pilot',
    'Psychotherapy': 'Psychotherapy 10',
    'Ride': 'Ride 10',
    'Science': 'Science 0',
    'Science_specializations': 'Science',
    'Search': 'Search 20',
    'SIGINT': 'SIGINT 0',
    'Stealth': 'Stealth 10',
    'Surgery': 'Surgery 0',
    'Survival': 'Survival 10',
    'Swim': 'Swim 20',
    'Unarmed Combat': 'Unarmed Combat 40',
    'Unnatural': 'Unnatural 0',
    // Foreign Language is handled by the main skill loop as specializations
    
    // Other Skills / Languages
    'otherSkill1Name': 'Foreign Languages and Other Skills 1',
    'otherSkill1Score': 'Foreign Languages and Other Skills 1 Score',
    'otherSkill2Name': 'Foreign Languages and Other Skills 2',
    'otherSkill2Score': 'Foreign Languages and Other Skills 2 Score',
    'otherSkill3Name': 'Foreign Languages and Other Skills 3',
    'otherSkill3Score': 'Foreign Languages and Other Skills 3 Score',
    'otherSkill4Name': 'Foreign Languages and Other Skills 4',
    'otherSkill4Score': 'Foreign Languages and Other Skills 4 Score',
    'otherSkill5Name': 'Foreign Languages and Other Skills 5',
    'otherSkill5Score': 'Foreign Languages and Other Skills 5 Score',
    'otherSkill6Name': 'Foreign Languages and Other Skills 6',
    'otherSkill6Score': 'Foreign Languages and Other Skills 6 Score',

    // Weapons (up to 6)
    weapon_a: 'WEAPONa',
    skill_a: 'SKILL a',
    baseRange_a: 'BASE RANGEa',
    damage_a: 'DAMAGEa',
    armorPiercing_a: 'ARMOR PIERCINGa',
    killDamage_a: 'KILL DAMAGEa',
    killRadius_a: 'KILL RADIUSa',
    ammo_a: 'AMMO a',

    weapon_b: 'WEAPONb',
    skill_b: 'SKILL b',
    baseRange_b: 'BASE RANGEb',
    damage_b: 'DAMAGEb',
    armorPiercing_b: 'ARMOR PIERCINGb',
    killDamage_b: 'KILL DAMAGEb',
    killRadius_b: 'KILL RADIUSb',
    ammo_b: 'AMMO b',
    
    weapon_c: 'WEAPONc',
    skill_c: 'SKILL c',
    baseRange_c: 'BASE RANGEc',
    damage_c: 'DAMAGEc',
    armorPiercing_c: 'ARMOR PIERCINGc',
    killDamage_c: 'KILL DAMAGEc',
    killRadius_c: 'KILL RADIUSc',
    ammo_c: 'AMMO c',

    weapon_d: 'WEAPONd',
    skill_d: 'SKILL d',
    baseRange_d: 'BASE RANGEd',
    damage_d: 'DAMAGEd',
    armorPiercing_d: 'ARMOR PIERCINGd',
    killDamage_d: 'KILL DAMAGEd',
    killRadius_d: 'KILL RADIUSd',
    ammo_d: 'AMMO d',
    
    weapon_e: 'WEAPONe',
    skill_e: 'SKILL e',
    baseRange_e: 'BASE RANGEe',
    damage_e: 'DAMAGEe',
    armorPiercing_e: 'ARMOR PIERCINGe',
    killDamage_e: 'KILL DAMAGEe',
    killRadius_e: 'KILL RADIUSe',
    ammo_e: 'AMMO e',

    weapon_f: 'WEAPONf',
    skill_f: 'SKILL f',
    baseRange_f: 'BASE RANGEf',
    damage_f: 'DAMAGEf',
    armorPiercing_f: 'ARMOR PIERCINGf',
    killDamage_f: 'KILL DAMAGEf',
    killRadius_f: 'KILL RADIUSf',
    ammo_f: 'AMMO f',

    // Special Trainings (up to 6)
    specialTraining_a_name: 'SPECIAL TRAININGa',
    specialTraining_a_stat: 'SKILL OR STATa',
    specialTraining_b_name: 'SPECIAL TRAININGb',
    specialTraining_b_stat: 'SKILL OR STATb',
    specialTraining_c_name: 'SPECIAL TRAININGc',
    specialTraining_c_stat: 'SKILL OR STATc',
    specialTraining_d_name: 'SPECIAL TRAININGd',
    specialTraining_d_stat: 'SKILL OR STATd',
    specialTraining_e_name: 'SPECIAL TRAININGe',
    specialTraining_e_stat: 'SKILL OR STATe',
    specialTraining_f_name: 'SPECIAL TRAININGf',
    specialTraining_f_stat: 'SKILL OR STATf',

    // New fields
    woundsAndAilments_2: '14 WOUNDS AND AILMENTS_2',
    armorAndGear: '15 ARMOR AND GEAR',
};