// sim-events/intelligence.ts
import type { EventBlueprint } from "../sim/types";
type Weight<T> = { item: T; w: number };

export const intelligenceEvents: Weight<EventBlueprint>[] = [
    { item: { kind: "Investigation", detail: "Conducted routine analysis of signals intelligence.", check: { type: 'skill', name: 'SIGINT' }, onSuccess: { skillChanges: [{ name: 'SIGINT', value: '1d4' }] }, onFailure: { skillChanges: [{ name: 'SIGINT', value: '1' }] } }, w: 20 },
    { item: { kind: "Transfer", detail: "Reassigned to a different analytical desk.", check: { type: 'attribute', name: 'INT' }, onSuccess: { skillChanges: [{ name: 'Bureaucracy', value: '1' }] }, onFailure: {} }, w: 15 },
    { item: { kind: "FamilyStrain", detail: "The secretive nature of the job created distance in a relationship.", check: { type: 'attribute', name: 'POW' }, onSuccess: {}, onFailure: { bondChange: -1 } }, w: 5 },
    { item: { kind: "Investigation", detail: "Ran a sensitive human intelligence (HUMINT) operation overseas.", check: { type: 'skill', name: 'HUMINT' }, onSuccess: { skillChanges: [{ name: 'HUMINT', value: '1d4' }] }, onFailure: { sanChange: -1, skillChanges: [{ name: 'HUMINT', value: '1' }] } }, w: 8 },
    { item: { kind: "Training", detail: "Underwent advanced polygraph and interrogation training.", check: { type: 'skill', name: 'Persuade' }, onSuccess: { skillChanges: [{ name: 'HUMINT', value: '1d4' }], sanChange: 1 }, onFailure: {} }, w: 7 },
    { item: { kind: "Coverup", detail: "Authored a sanitized report to conceal operational failures from oversight.", check: { type: 'attribute', name: 'INT' }, onSuccess: { sanChange: -1 }, onFailure: { sanChange: -2 }, flags: ["classified"] }, w: 7 },
    { item: { kind: "Burned", detail: "An asset was compromised, forcing an emergency exfiltration.", check: { type: 'attribute', name: 'DEX' }, onSuccess: { skillChanges: [{ name: 'Stealth', value: '1d4' }] }, onFailure: { sanChange: -2 } }, w: 4 },
    { item: { kind: "DataBreach", detail: "A secure network was breached, leading to a frantic internal damage assessment.", check: { type: 'skill', name: 'Computer Science' }, onSuccess: { skillChanges: [{ name: 'Computer Science', value: '1d4' }] }, onFailure: { sanChange: -2 } }, w: 4 },
    { item: { kind: "BudgetCuts", detail: "Program budget cuts forced the cancellation of a key project.", check: { type: 'skill', name: 'Bureaucracy' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 6 },
    { item: { kind: "DGIncident", detail: "Analyzed intercepted communications that contained non-human patterns.", check: { type: 'skill', name: 'SIGINT' }, onSuccess: { skillChanges: [{ name: 'Unnatural', value: '1' }] }, onFailure: { sanChange: -5, skillChanges: [{ name: 'Unnatural', value: '1d4' }] }, flags: ["classified"] }, w: 3 },
    { item: { kind: "DGIncident", detail: "Debriefed a field agent who had gone insane after a mission.", check: { type: 'skill', name: 'Psychotherapy' }, onSuccess: { skillChanges: [{ name: 'Unnatural', value: '1' }] }, onFailure: { sanChange: -2, skillChanges: [{ name: 'Unnatural', value: '1' }] } }, w: 2 },
    { item: { kind: "Investigation", detail: "Participated in a counter-intelligence operation to hunt for a suspected mole.", check: { type: 'skill', name: 'HUMINT' }, onSuccess: { skillChanges: [{ name: 'Criminology', value: '1d4' }] }, onFailure: { sanChange: -2 } }, w: 4 },
    { item: { kind: "SpecialAssignment", detail: "Designed a psychological operations (PSYOPS) campaign.", check: { type: 'skill', name: 'Persuade' }, onSuccess: { skillChanges: [{ name: 'Art', value: '1d4' }] }, onFailure: { sanChange: -1 } }, w: 3 },
    { item: { kind: "Deploy", detail: "Served a tour in a hostile, denied-area environment.", check: { type: 'skill', name: 'Stealth' }, onSuccess: { skillChanges: [{ name: 'Survival', value: '1d4' }, { name: 'Stealth', value: '1d4' }] }, onFailure: { sanChange: -2, attributeChange: { name: 'CON', value: -1 } } }, w: 5 },
    { item: { kind: "Investigation", detail: "Underwent a grueling series of polygraph examinations as part of a security review.", check: { type: 'attribute', name: 'POW' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 7 },
    { item: { kind: "SpecialAssignment", detail: "Managed a network of safe houses in a foreign city.", check: { type: 'skill', name: 'Stealth' }, onSuccess: { skillChanges: [{ name: 'Stealth', value: '1d4' }] }, onFailure: { skillChanges: [{ name: 'Stealth', value: '1' }] } }, w: 6 },
    { item: { kind: "SpecialAssignment", detail: "Tasked with redacting thousands of pages of documents for public release.", check: { type: 'skill', name: 'Bureaucracy' }, onSuccess: { skillChanges: [{ name: 'Bureaucracy', value: '1d4' }] }, onFailure: { sanChange: -1 } }, w: 8 },
    { item: { kind: "SpecialAssignment", detail: "Briefed a panel of high-level, skeptical officials on a sensitive matter.", check: { type: 'skill', name: 'Persuade' }, onSuccess: { sanChange: 1 }, onFailure: { sanChange: -1 } }, w: 5 },
    { item: { kind: "Investigation", detail: "Analyzed satellite imagery (IMINT) to track a target.", check: { type: 'skill', name: 'Search' }, onSuccess: { skillChanges: [{ name: 'Science', value: '1d4' }] }, onFailure: { skillChanges: [{ name: 'Science', value: '1' }] } }, w: 7 },
];
