// sim-events/lawEnforcement.ts
import type { EventBlueprint } from "../sim/types";
type Weight<T> = { item: T; w: number };

export const lawEnforcementEvents: Weight<EventBlueprint>[] = [
    { item: { kind: "Investigation", detail: "Worked a series of routine cases.", check: { type: 'skill', name: 'Criminology' }, onSuccess: { skillChanges: [{ name: 'Criminology', value: '1d4' }] }, onFailure: { skillChanges: [{ name: 'Criminology', value: '1' }] } }, w: 20 },
    { item: { kind: "Transfer", detail: "Assigned to a different precinct or department.", check: { type: 'attribute', name: 'CHA' }, onSuccess: { skillChanges: [{ name: 'Bureaucracy', value: '1' }] }, onFailure: {} }, w: 15 },
    { item: { kind: "Commendation", detail: "Received a departmental commendation for closing a case.", check: { type: 'attribute', name: 'INT' }, onSuccess: { sanChange: 1 }, onFailure: {} }, w: 10 },
    { item: { kind: "Testimony", detail: "Provided key testimony in a major trial.", check: { type: 'skill', name: 'Persuade' }, onSuccess: { skillChanges: [{ name: 'Law', value: '1d4' }], sanChange: 1 }, onFailure: { sanChange: -1 } }, w: 7 },
    { item: { kind: "Investigation", detail: "Led a high-profile, media-intensive investigation.", check: { type: 'skill', name: 'Persuade' }, onSuccess: { skillChanges: [{ name: 'Persuade', value: '1d4' }] }, onFailure: { sanChange: -1 } }, w: 7 },
    { item: { kind: "Injury", detail: "Injured during the apprehension of a suspect.", check: { type: 'attribute', name: 'STR' }, onSuccess: {}, onFailure: { attributeChange: { name: 'CON', value: -1 }, sanChange: -1 } }, w: 6 },
    { item: { kind: "DisciplinaryAction", detail: "Faced an Internal Affairs review.", check: { type: 'attribute', name: 'POW' }, onSuccess: {}, onFailure: { sanChange: -2 } }, w: 5 },
    { item: { kind: "Undercover", detail: "Completed a short-term undercover assignment.", check: { type: 'skill', name: 'Stealth' }, onSuccess: { skillChanges: [{ name: 'Disguise', value: '1d4' }, { name: 'Persuade', value: '1d4' }] }, onFailure: { sanChange: -1 } }, w: 4 },
    { item: { kind: "Suspension", detail: "Placed on administrative leave pending an internal investigation.", check: { type: 'attribute', name: 'POW' }, onSuccess: { sanChange: -1 }, onFailure: { sanChange: -2 } }, w: 5 },
    { item: { kind: "PartnerDeath", detail: "Partner was killed in the line of duty under bizarre circumstances.", check: { type: 'attribute', name: 'POW' }, onSuccess: { sanChange: -2 }, onFailure: { sanChange: -5, bondChange: -1 } }, w: 2 },
    { item: { kind: "FieldMission", detail: "Participated in a high-risk tactical raid.", check: { type: 'skill', name: 'Firearms' }, onSuccess: { skillChanges: [{ name: 'Firearms', value: '1d4' }] }, onFailure: { sanChange: -1 } }, w: 8 },
    { item: { kind: "Audit", detail: "Evidence room was audited, requiring extensive paperwork.", check: { type: 'skill', name: 'Bureaucracy' }, onSuccess: { skillChanges: [{ name: 'Bureaucracy', value: '1d4' }] }, onFailure: {} }, w: 6 },
    { item: { kind: "DGIncident", detail: "Investigated a crime scene with physically impossible characteristics.", check: { type: 'attribute', name: 'INT' }, onSuccess: { skillChanges: [{ name: 'Unnatural', value: '1' }] }, onFailure: { sanChange: -5, skillChanges: [{ name: 'Unnatural', value: '1d4' }] }, flags: ["classified"] }, w: 3 },
    { item: { kind: "Coverup", detail: "Forced to sign off on a case report that omitted key, unexplainable evidence.", check: { type: 'skill', name: 'Bureaucracy' }, onSuccess: { sanChange: -1 }, onFailure: { sanChange: -2 }, flags: ["classified"] }, w: 4 },
    { item: { kind: "SpecialAssignment", detail: "Assigned to a riot control unit during a period of civil unrest.", check: { type: 'attribute', name: 'STR' }, onSuccess: { skillChanges: [{ name: 'Melee Weapons', value: '1' }] }, onFailure: { sanChange: -1, attributeChange: { name: 'CON', value: -1 } } }, w: 5 },
    { item: { kind: "Investigation", detail: "Handled a confidential informant whose information proved unreliable.", check: { type: 'skill', name: 'HUMINT' }, onSuccess: {}, onFailure: { sanChange: -1, skillChanges: [{ name: 'HUMINT', value: '1' }] } }, w: 6 },
    { item: { kind: "SpecialAssignment", detail: "Executed a high-risk warrant on a fortified location.", check: { type: 'skill', name: 'Demolitions' }, onSuccess: { skillChanges: [{ name: 'Firearms', value: '1d4' }] }, onFailure: { sanChange: -2, bondChange: -1 } }, w: 4 },
    { item: { kind: "SpecialAssignment", detail: "Forced to participate in a clumsy community outreach program.", check: { type: 'attribute', name: 'CHA' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 7 },
    { item: { kind: "Investigation", detail: "Assigned to a cold case, spending a year digging through old files.", check: { type: 'skill', name: 'Search' }, onSuccess: { skillChanges: [{ name: 'Criminology', value: '1d4' }, { name: 'Search', value: '1d4' }] }, onFailure: { skillChanges: [{ name: 'Criminology', value: '1' }] } }, w: 6 },
    { item: { kind: "Training", detail: "Attended an advanced course in forensic analysis.", check: { type: 'attribute', name: 'INT' }, onSuccess: { skillChanges: [{ name: 'Forensics', value: '1d4' }] }, onFailure: { skillChanges: [{ name: 'Forensics', value: '1' }] } }, w: 7 },
    { item: { kind: "Investigation", detail: "Spent weeks on a tedious stakeout with a difficult partner.", check: { type: 'skill', name: 'Alertness' }, onSuccess: { skillChanges: [{ name: 'Alertness', value: '1d4' }] }, onFailure: { sanChange: -1 } }, w: 8 },
    { item: { kind: "Investigation", detail: "An investigation was hampered by a jurisdictional dispute with another agency.", check: { type: 'skill', name: 'Bureaucracy' }, onSuccess: {}, onFailure: { sanChange: -1, skillChanges: [{ name: 'Bureaucracy', value: '1d4' }] } }, w: 5 },
];
