// sim-events/military.ts
import type { EventBlueprint } from "../sim/types";
type Weight<T> = { item: T; w: number };

export const militaryEvents: Weight<EventBlueprint>[] = [
    { item: { kind: "Deploy", detail: "Routine overseas deployment.", check: { type: 'attribute', name: 'CON' }, onSuccess: { skillChanges: [{ name: 'Survival', value: '1d4' }] }, onFailure: { skillChanges: [{ name: 'Survival', value: '1' }], sanChange: -1 } }, w: 20 },
    { item: { kind: "Transfer", detail: "Reassigned to a new domestic base.", check: { type: 'attribute', name: 'CHA' }, onSuccess: { skillChanges: [{ name: 'Bureaucracy', value: '1' }] }, onFailure: {} }, w: 15 },
    { item: { kind: "Commendation", detail: "Received a unit citation for exceptional performance.", check: { type: 'attribute', name: 'POW' }, onSuccess: { sanChange: 1 }, onFailure: {} }, w: 10 },
    { item: { kind: "Training", detail: "Completed a specialized training course (e.g., SERE).", check: { type: 'attribute', name: 'CON' }, onSuccess: { skillChanges: [{ name: 'Survival', value: '1d4' }, { name: 'Navigate', value: '1d4' }], sanChange: 1 }, onFailure: { skillChanges: [{ name: 'Survival', value: '1' }] } }, w: 8 },
    { item: { kind: "Deploy", detail: "Deployed to active combat zone.", check: { type: 'skill', name: 'Firearms' }, onSuccess: { skillChanges: [{ name: 'Firearms', value: '1d4' }], sanChange: -1 }, onFailure: { skillChanges: [{ name: 'Firearms', value: '1' }], sanChange: -2 } }, w: 8 },
    { item: { kind: "Injury", detail: "Sustained a non-critical injury during training.", check: { type: 'attribute', name: 'DEX' }, onSuccess: {}, onFailure: { sanChange: -1, attributeChange: { name: 'DEX', value: -1 } } }, w: 7 },
    { item: { kind: "Investigation", detail: "Participated in a JAG investigation.", check: { type: 'skill', name: 'Law' }, onSuccess: { skillChanges: [{ name: 'Law', value: '1d4' }] }, onFailure: { skillChanges: [{ name: 'Law', value: '1' }] } }, w: 5 },
    { item: { kind: "FamilyStrain", detail: "Extended deployment caused strain on a personal relationship.", check: { type: 'attribute', name: 'CHA' }, onSuccess: {}, onFailure: { bondChange: -1 } }, w: 5 },
    { item: { kind: "DisciplinaryAction", detail: "Faced a non-judicial punishment for a minor infraction.", check: { type: 'attribute', name: 'POW' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 4 },
    { item: { kind: "SpecialAssignment", detail: "Assigned to a joint task force with other agencies.", check: { type: 'skill', name: 'Bureaucracy' }, onSuccess: { skillChanges: [{ name: 'Bureaucracy', value: '1d4' }, { name: 'HUMINT', value: '1d4' }] }, onFailure: {} }, w: 3 },
    { item: { kind: "Coverup", detail: "Involved in sanitizing an after-action report for a botched operation.", check: { type: 'attribute', name: 'INT' }, onSuccess: { skillChanges: [{ name: 'Bureaucracy', value: '1d4' }] }, onFailure: { sanChange: -1, skillChanges: [{ name: 'Bureaucracy', value: '1' }] }, flags: ["classified"] }, w: 3 },
    { item: { kind: "PsychEval", detail: "Underwent a mandatory psychological evaluation.", check: { type: 'attribute', name: 'POW' }, onSuccess: {}, onFailure: {} }, w: 6 },
    { item: { kind: "DeskDuty", detail: "Assigned to a year of administrative desk duty.", check: { type: 'attribute', name: 'INT' }, onSuccess: { skillChanges: [{ name: 'Bureaucracy', value: '1d4' }] }, onFailure: { sanChange: -1 } }, w: 7 },
    { item: { kind: "DGIncident", detail: "Participated in the retrieval of an asset that was not entirely human.", check: { type: 'attribute', name: 'POW' }, onSuccess: { skillChanges: [{ name: 'Unnatural', value: '1' }] }, onFailure: { sanChange: -5, skillChanges: [{ name: 'Unnatural', value: '1d4' }] }, flags: ["classified"] }, w: 2 },
    { item: { kind: "SpecialAssignment", detail: "Assigned to a logistics and supply chain management role.", check: { type: 'skill', name: 'Bureaucracy' }, onSuccess: { skillChanges: [{ name: 'Bureaucracy', value: '1d4' }] }, onFailure: { skillChanges: [{ name: 'Bureaucracy', value: '1' }] } }, w: 7 },
    { item: { kind: "Testimony", detail: "Testified in a high-profile court-martial.", check: { type: 'skill', name: 'Law' }, onSuccess: { skillChanges: [{ name: 'Law', value: '1d4' }] }, onFailure: { sanChange: -1 } }, w: 4 },
    { item: { kind: "Training", detail: "Assigned to recruitment duty for a year.", check: { type: 'skill', name: 'Persuade' }, onSuccess: { skillChanges: [{ name: 'Persuade', value: '1d4' }] }, onFailure: {} }, w: 6 },
    { item: { kind: "Deploy", detail: "Participated in a joint-service exercise with allied nations.", check: { type: 'attribute', name: 'CHA' }, onSuccess: { skillChanges: [{ name: 'Military Science', value: '1d4' }] }, onFailure: {} }, w: 8 },
    { item: { kind: "Injury", detail: "Survived a catastrophic equipment failure during a mission.", check: { type: 'attribute', name: 'POW' }, onSuccess: { sanChange: 1 }, onFailure: { sanChange: -2, maxHpChange: '1d3' } }, w: 3 },
    { item: { kind: "Investigation", detail: "Dealt with a corrupt superior officer, leading to an internal investigation.", check: { type: 'attribute', name: 'POW' }, onSuccess: { skillChanges: [{ name: 'Bureaucracy', value: '1' }] }, onFailure: { sanChange: -2 } }, w: 2 },
    { item: { kind: "SpecialAssignment", detail: "Guarded a high-value asset in a secure location.", check: { type: 'skill', name: 'Alertness' }, onSuccess: { skillChanges: [{ name: 'Alertness', value: '1d4' }] }, onFailure: { skillChanges: [{ name: 'Alertness', value: '1' }] } }, w: 7 },
    { item: { kind: "Deploy", detail: "Deployed on a humanitarian mission after a natural disaster.", check: { type: 'attribute', name: 'CHA' }, onSuccess: { sanChange: 1 }, onFailure: { sanChange: -1 } }, w: 5 },
];
