// sim-events/weird.ts
import type { EventBlueprint } from "../sim/types";
type Weight<T> = { item: T; w: number };

export const weirdEvents: Weight<EventBlueprint>[] = [
    { item: { kind: "Weird", detail: "Woke up with a memory of a day that never happened.", check: { type: 'attribute', name: 'POW' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 10 },
    { item: { kind: "Weird", detail: "A phone call consisted of static that formed into your name.", check: { type: 'attribute', name: 'INT' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 10 },
    { item: { kind: "Weird", detail: "Saw a face in a crowd that had no features.", check: { type: 'attribute', name: 'POW' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 8 },
    { item: { kind: "Weird", detail: "Found a book in a used bookstore written in a language that doesn't exist.", check: { type: 'skill', name: 'Occult' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 7 },
    { item: { kind: "Weird", detail: "A street camera seemed to follow you for three blocks.", check: { type: 'skill', name: 'Alertness' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 10 },
    { item: { kind: "Weird", detail: "Your reflection in a window didn't move for a full second.", check: { type: 'attribute', name: 'POW' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 6 },
    { item: { kind: "Weird", detail: "Received an email from your own address, dated ten years in the future.", check: { type: 'skill', name: 'Computer Science' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 5 },
    { item: { kind: "Weird", detail: "Heard a radio broadcast detailing your exact actions from the previous day.", check: { type: 'skill', name: 'SIGINT' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 4 },
    { item: { kind: "Weird", detail: "All the clocks in your home stopped at the exact same time.", check: { type: 'attribute', name: 'INT' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 9 },
    { item: { kind: "Weird", detail: "A stranger on the street whispered a secret you've never told anyone.", check: { type: 'attribute', name: 'CHA' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 3 },
    { item: { kind: "Weird", detail: "A shadow detached from a lamppost and slithered into an alley.", check: { type: 'skill', name: 'Alertness' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 7 },
    { item: { kind: "Weird", detail: "Found a perfect, fossilized insect in your sealed container of oatmeal.", check: { type: 'attribute', name: 'INT' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 8 },
    { item: { kind: "Weird", detail: "A song you've never heard before was stuck in your head, and you knew every word.", check: { type: 'attribute', name: 'POW' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 6 },
    { item: { kind: "Weird", detail: "A childhood toy appeared on your pillow, despite being lost 20 years ago.", check: { type: 'attribute', name: 'POW' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 5 },
    { item: { kind: "Weird", detail: "For three hours, every person you saw had the exact same face.", check: { type: 'attribute', name: 'POW' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 4 },
    { item: { kind: "Weird", detail: "A door in your home opened into a room that isn't there.", check: { type: 'skill', name: 'Alertness' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 3 },
    { item: { kind: "Weird", detail: "You dialed a wrong number and the person who answered knew your name.", check: { type: 'attribute', name: 'INT' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 9 },
    { item: { kind: "Weird", detail: "A cloud in the sky formed into a perfect, geometric symbol.", check: { type: 'skill', name: 'Occult' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 7 },
    { item: { kind: "Weird", detail: "The text on a street sign briefly rearranged itself into a warning.", check: { type: 'skill', name: 'Alertness' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 8 },
    { item: { kind: "Weird", detail: "A stray cat followed you home, but it had no eyes.", check: { type: 'attribute', name: 'POW' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 6 },
    { item: { kind: "Weird", detail: "You coughed up a small, smooth, black stone of unknown origin.", check: { type: 'attribute', name: 'CON' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 5 },
    { item: { kind: "Weird", detail: "A recurring dream of a black star became intensely, physically real for a moment.", check: { type: 'attribute', name: 'POW' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 4 },
    { item: { kind: "Weird", detail: "The GPS in your car directed you down a road that doesn't exist on any map.", check: { type: 'skill', name: 'Navigate' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 9 },
    { item: { kind: "Weird", detail: "You found a file on your computer that you don't remember creating, containing your own autopsy report.", check: { type: 'skill', name: 'Computer Science' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 3 },
    { item: { kind: "Weird", detail: "An old photograph in your wallet changed; you were no longer in the picture.", check: { type: 'attribute', name: 'POW' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 5 },
    { item: { kind: "Weird", detail: "You saw a bird fly backwards for ten seconds.", check: { type: 'skill', name: 'Alertness' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 10 },
    { item: { kind: "Weird", detail: "A book on your shelf was replaced with an identical copy, but with a different ending.", check: { type: 'skill', name: 'Search' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 7 },
    { item: { kind: "Weird", detail: "Your teeth ached in unison with a distant, rhythmic hum.", check: { type: 'attribute', name: 'CON' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 8 },
    { item: { kind: "Weird", detail: "A number station broadcast began reading your social security number.", check: { type: 'skill', name: 'SIGINT' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 4 },
    { item: { kind: "Weird", detail: "You found a key in your pocket that fits no lock you own, but feels warm to the touch.", check: { type: 'attribute', name: 'POW' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 9 },
    { item: { kind: "Weird", detail: "The rain outside your window was falling upwards.", check: { type: 'skill', name: 'Science' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 6 },
    { item: { kind: "Weird", detail: "A familiar path home led you to a neighborhood you've never seen before.", check: { type: 'skill', name: 'Navigate' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 8 },
    { item: { kind: "Weird", detail: "You found a note you wrote to yourself in a handwriting that is not your own.", check: { type: 'attribute', name: 'INT' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 7 },
    { item: { kind: "Weird", detail: "A piece of junk mail was addressed to you, but from a company that won't exist for another 50 years.", check: { type: 'attribute', name: 'INT' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 6 },
    { item: { kind: "Weird", detail: "You saw a deer in the woods that walked on its hind legs for a few steps.", check: { type: 'skill', name: 'Survival' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 5 },
    { item: { kind: "Weird", detail: "The smell of ozone and old pennies filled your room for exactly one minute.", check: { type: 'attribute', name: 'CON' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 9 },
    { item: { kind: "Weird", detail: "You answered a knock at the door to find nobody there, only a pile of dead leaves arranged in a spiral.", check: { type: 'attribute', name: 'POW' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 8 },
    { item: { kind: "Weird", detail: "A TV show you were watching was interrupted by a single, unblinking eye for 3 seconds.", check: { type: 'skill', name: 'Alertness' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 7 },
    { item: { kind: "Weird", detail: "You suddenly understood a foreign language perfectly for half an hour.", check: { type: 'skill', name: 'Language' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 6 },
    { item: { kind: "Weird", detail: "A patch of your skin briefly became translucent, showing the muscle underneath.", check: { type: 'attribute', name: 'CON' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 4 },
    { item: { kind: "Weird", detail: "The stars in the night sky rearranged themselves into an unfamiliar constellation.", check: { type: 'skill', name: 'Navigate' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 3 },
    { item: { kind: "Weird", detail: "You received a phone notification for an event that happened yesterday.", check: { type: 'attribute', name: 'INT' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 10 },
    { item: { kind: "Weird", detail: "A conversation with a colleague contained a sentence that you both remember differently.", check: { type: 'attribute', name: 'POW' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 9 },
    { item: { kind: "Weird", detail: "You saw an insect with too many legs scuttle under your fridge.", check: { type: 'skill', name: 'Science' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 8 },
    { item: { kind: "Weird", detail: "A public announcement on the subway was spoken in a dead language.", check: { type: 'skill', name: 'Language' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 7 },
    { item: { kind: "Weird", detail: "You found a receipt in your pocket for items you have no memory of buying.", check: { type: 'skill', name: 'Search' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 9 },
    { item: { kind: "Weird", detail: "The sound of your own breathing came from the other side of the room.", check: { type: 'skill', name: 'Alertness' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 6 },
    { item: { kind: "Weird", detail: "A vending machine dispensed a can with a blank, silver label.", check: { type: 'attribute', name: 'INT' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 10 },
    { item: { kind: "Weird", detail: "Your car keys unlocked and started a stranger's identical car.", check: { type: 'skill', name: 'Craft' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 8 },
    { item: { kind: "Weird", detail: "A word in a newspaper article was printed in a typeface that seemed to crawl.", check: { type: 'attribute', name: 'POW' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 7 },
    { item: { kind: "Weird", detail: "You felt a sharp, sudden pain as if from an old wound you've never had.", check: { type: 'attribute', name: 'CON' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 9 },
    { item: { kind: "Weird", detail: "A flock of birds flying overhead suddenly dropped from the sky, dead.", check: { type: 'skill', name: 'Science' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 5 },
    { item: { kind: "Weird", detail: "You recognized a suspect in a cold case file as someone from your dreams.", check: { type: 'skill', name: 'Criminology' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 6 },
    { item: { kind: "Weird", detail: "A perfectly circular patch of silence descended on your location for five minutes.", check: { type: 'attribute', name: 'POW' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 8 },
    { item: { kind: "Weird", detail: "Your fingerprints left a scorch mark on a cold glass of water.", check: { type: 'attribute', name: 'CON' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 4 },
    { item: { kind: "Weird", detail: "You saw a man on a security camera feed who wasn't there in the room.", check: { type: 'skill', name: 'SIGINT' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 7 },
    { item: { kind: "Weird", detail: "A book you were reading had a new chapter in it the second time you opened it.", check: { type: 'attribute', name: 'INT' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 8 },
    { item: { kind: "Weird", detail: "A spiderweb in your window spelled out a single, comprehensible word.", check: { type: 'skill', name: 'Occult' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 6 },
    { item: { kind: "Weird", detail: "The moon appeared to be twice its normal size for a few minutes.", check: { type: 'skill', name: 'Alertness' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 9 },
    { item: { kind: "Weird", detail: "You blinked and found yourself in a different chair on the other side of the table.", check: { type: 'attribute', name: 'DEX' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 4 },
    { item: { kind: "Weird", detail: "A fire alarm went off, but the sound was a chorus of human screams.", check: { type: 'attribute', name: 'POW' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 5 },
    { item: { kind: "Weird", detail: "You found a children's drawing of a horrific monster, signed with your name.", check: { type: 'attribute', name: 'POW' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 6 },
    { item: { kind: "Weird", detail: "A puddle on the sidewalk reflected a sky filled with green stars.", check: { type: 'skill', name: 'Alertness' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 8 },
    { item: { kind: "Weird", detail: "You felt the distinct sensation of being watched from inside your own head.", check: { type: 'attribute', name: 'POW' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 4 },
    { item: { kind: "Weird", detail: "A parked car's alarm chirped a perfect musical scale.", check: { type: 'attribute', name: 'INT' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 10 },
    { item: { kind: "Weird", detail: "An incoming call on your phone had no number, just a string of symbols.", check: { type: 'skill', name: 'SIGINT' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 9 },
    { item: { kind: "Weird", detail: "You saw a mannequin in a store window turn its head to follow you.", check: { type: 'skill', name: 'Alertness' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 8 },
    { item: { kind: "Weird", detail: "A computer error message simply read 'It knows you are here.'", check: { type: 'skill', name: 'Computer Science' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 7 },
    { item: { kind: "Weird", detail: "You found a single, gray feather in a locked, sterile room.", check: { type: 'skill', name: 'Search' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 9 },
    { item: { kind: "Weird", detail: "A radio talk show host started answering the questions in your mind.", check: { type: 'attribute', name: 'POW' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 5 },
    { item: { kind: "Weird", detail: "The water from your tap ran black for 13 seconds, then cleared.", check: { type: 'attribute', name: 'CON' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 8 },
    { item: { kind: "Weird", detail: "A crack in the pavement looked exactly like the coastline of an unknown continent.", check: { type: 'skill', name: 'Navigate' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 9 },
    { item: { kind: "Weird", detail: "You heard footsteps following you that made no sound.", check: { type: 'skill', name: 'Alertness' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 7 },
    { item: { kind: "Weird", detail: "You passed a street performer who was playing an instrument with no moving parts.", check: { type: 'attribute', name: 'INT' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 8 },
    { item: { kind: "Weird", detail: "You woke up with your muscles aching as if from a full day of labor you don't remember.", check: { type: 'attribute', name: 'CON' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 9 },
    { item: { kind: "Weird", detail: "A library book you checked out had your own anxious marginalia in the notes.", check: { type: 'attribute', name: 'INT' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 7 },
    { item: { kind: "Weird", detail: "The pattern of wood grain on a table shifted and swirled like smoke.", check: { type: 'attribute', name: 'POW' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 6 },
    { item: { kind: "Weird", detail: "You found a small, intricate metal gear in your morning coffee.", check: { type: 'skill', name: 'Search' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 8 },
    { item: { kind: "Weird", detail: "A dog barked at you, but the sound was your own name, spoken perfectly.", check: { type: 'attribute', name: 'POW' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 5 },
    { item: { kind: "Weird", detail: "Your voice on a recording was distorted, speaking in reverse.", check: { type: 'skill', name: 'SIGINT' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 7 },
    { item: { kind: "Weird", detail: "You felt a sudden, intense nostalgia for a place that has never existed.", check: { type: 'attribute', name: 'POW' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 8 },
    { item: { kind: "Weird", detail: "You saw a license plate that was a mathematical impossibility.", check: { type: 'skill', name: 'Science' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 6 },
    { item: { kind: "Weird", detail: "You received a letter in the mail that had been postmarked in the 19th century.", check: { type: 'skill', name: 'History' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 7 },
    { item: { kind: "Weird", detail: "A crossword puzzle's solution was a coherent and threatening message.", check: { type: 'attribute', name: 'INT' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 8 },
    { item: { kind: "Weird", detail: "You couldn't recognize your own face in the mirror for several seconds.", check: { type: 'attribute', name: 'POW' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 5 },
    { item: { kind: "Weird", detail: "A power outage affected only your building, and everything glowed with a faint purple light.", check: { type: 'skill', name: 'Alertness' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 6 },
    { item: { kind: "Weird", detail: "You saw a painting in a museum where one of the figures was wearing your watch.", check: { type: 'skill', name: 'Art' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 7 },
    { item: { kind: "Weird", detail: "A smell from your childhood filled the air, but it was coming from a sewer grate.", check: { type: 'attribute', name: 'POW' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 8 },
    { item: { kind: "Weird", detail: "You found sand in your shoes, despite not having been to a beach in years.", check: { type: 'attribute', name: 'INT' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 9 },
    { item: { kind: "Weird", detail: "The automatic doors at a supermarket refused to open for you, but opened for everyone else.", check: { type: 'attribute', name: 'CHA' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 10 },
    { item: { kind: "Weird", detail: "An echo in a hallway repeated what you said, but in a different voice.", check: { type: 'attribute', name: 'POW' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 6 },
    { item: { kind: "Weird", detail: "You felt a raindrop on your arm indoors, under a solid ceiling.", check: { type: 'skill', name: 'Alertness' }, onSuccess: {}, onFailure: { sanChange: -1 } }, w: 9 },
    { item: { kind: "Weird", detail: "The magnetic strip on your credit card was replaced by a line of cuneiform script.", check: { type: 'skill', name: 'Occult' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 5 },
    { item: { kind: "Weird", detail: "You opened a can of soup to find it was full of twitching, metallic insects.", check: { type: 'attribute', name: 'CON' }, onSuccess: { }, onFailure: { sanChange: -1 } }, w: 4 },
];
