import type { DGItem } from '../types';

export const firearms: DGItem[] = [
  {
    section: 'Firearms',
    name: 'Light Pistol',
    shortName: 'Light Pistol',
    skill: 'Firearms',
    damage: '1D8',
    armorPiercing: 'N/A',
    expense: 'Standard',
    baseRange: '10 m',
    lethality: '5%',
    ammoCapacity: '7',
    description: "Revolver capacity: 6. Examples: .22 LR, .32 ACP, .380 ACP, .38 Special: S&W Model 36 Chief's Special, Walther PPK.",
    isRestricted: false,
    sourceType: 'core'
  },
  {
    section: 'Firearms',
    name: 'Medium Pistol',
    shortName: 'Medium Pistol',
    skill: 'Firearms',
    damage: '1D10',
    armorPiercing: 'N/A',
    expense: 'Standard',
    baseRange: '15 m',
    lethality: '5%',
    ammoCapacity: '15',
    description: "Revolver capacity: 6. Examples: 9x19 mm, .40 S&W, .45 ACP: Beretta Mod 92FS (M9), Colt M1911A1, Glock 17, Glock 22.",
    isRestricted: false,
    sourceType: 'core'
  },
  {
    section: 'Firearms',
    name: 'Heavy Pistol',
    shortName: 'Heavy Pistol',
    skill: 'Firearms',
    damage: '1D12',
    armorPiercing: 'N/A',
    expense: 'Standard',
    baseRange: '20 m',
    lethality: '10%',
    ammoCapacity: '10',
    description: "RESTRICTED. Not standard issue; requires special justification. Revolver capacity: 6. Examples: 10x25mm Auto, .357 Magnum, .44 Magnum, .50 AE: Colt Delta Elite, Glock 20, S&W Model 13.",
    isRestricted: true,
    sourceType: 'core'
  },
  {
    section: 'Firearms',
    name: 'Shotgun (firing shot)',
    shortName: 'Shotgun (shot)',
    skill: 'Firearms',
    damage: '2D8',
    armorPiercing: 'N/A',
    expense: 'Standard',
    baseRange: '75 m',
    lethality: '20%',
    ammoCapacity: '5',
    description: "Lethality rating only applies within 10m. Damage is reduced at longer ranges. Examples (12-gauge): Mossberg Model 500, Remington Model 870, Ruger Red Label.",
    isRestricted: false,
    sourceType: 'core'
  },
  {
    section: 'Firearms',
    name: 'Shotgun (firing slug)',
    shortName: 'Shotgun (slug)',
    skill: 'Firearms',
    damage: '2D8',
    armorPiercing: '3',
    expense: 'Standard',
    baseRange: '75 m',
    lethality: '15%',
    ammoCapacity: '5',
    description: "Damage reduced to 2D6 beyond base range.",
    isRestricted: false,
    sourceType: 'core'
  },
  {
    section: 'Firearms',
    name: 'Shotgun (firing nonlethal)',
    shortName: 'Shotgun (nonlethal)',
    skill: 'Firearms',
    damage: '1D6 and Stunned',
    armorPiercing: 'N/A',
    expense: 'Standard',
    baseRange: '10 m',
    lethality: 'N/A',
    ammoCapacity: '5',
    description: "Nonlethal rounds.",
    isRestricted: false,
    sourceType: 'core'
  },
  {
    section: 'Firearms',
    name: 'Light Rifle or Carbine',
    shortName: 'Light Rifle/Carbine',
    skill: 'Firearms',
    damage: '1D12',
    armorPiercing: '3',
    expense: 'Standard',
    baseRange: '100 m',
    lethality: '10%',
    ammoCapacity: '10 or 30',
    description: "RESTRICTED IF CAPABLE OF FULLY AUTOMATIC FIRE. Use the Lethality rating if firing bursts. Examples: 5.45x39mm, 5.56mm NATO: AR-15, Colt M4, FN SCAR-L. Heavier rounds such as 7.62x39mm (AK-47) and .30-30 Winchester inflict 1D12+1 damage.",
    isRestricted: true,
    sourceType: 'core'
  },
  {
    section: 'Firearms',
    name: 'Submachine Gun (SMG)',
    shortName: 'Submachine Gun',
    skill: 'Firearms',
    damage: '1D10',
    armorPiercing: 'N/A',
    expense: 'Unusual',
    baseRange: '50 m',
    lethality: '10%',
    ammoCapacity: '30',
    description: "RESTRICTED IF CAPABLE OF FULLY AUTOMATIC FIRE. Use the Lethality rating if firing bursts. Examples: 5.7x28 mm, 9x19 mm, .45 ACP: B&T MP2, FN P90, H&K MP5, IMI Uzi, KRISS Vector, MAC-Ingram M10.",
    isRestricted: true,
    sourceType: 'core'
  },
  {
    section: 'Firearms',
    name: 'Heavy Rifle',
    shortName: 'Heavy Rifle',
    skill: 'Firearms',
    damage: '1D12+2',
    armorPiercing: '5',
    expense: 'Unusual',
    baseRange: '150 m',
    lethality: '10%',
    ammoCapacity: '10 or 20',
    description: "RESTRICTED IF CAPABLE OF FULLY AUTOMATIC FIRE. Use the Lethality rating if firing bursts. Examples: 7.62 mm NATO, 7.62x54mm, .30-06: H&K G3, FN FAL, Izmash SVD, M1 Garand, Remington Model 700 (M24).",
    isRestricted: true,
    sourceType: 'core'
  },
  {
    section: 'Firearms',
    name: 'Very Heavy Rifle',
    shortName: 'Very Heavy Rifle',
    skill: 'Firearms',
    damage: 'N/A',
    armorPiercing: '5',
    expense: 'Major',
    baseRange: '250 m',
    lethality: '20%',
    ammoCapacity: '10',
    description: "Examples: .408 CheyTac, .50 Browning: Barrett Model 82A1, CheyTac M200.",
    isRestricted: true,
    sourceType: 'core'
  },
];
