import type { DGItem } from '../types';

export const heavyWeapons: DGItem[] = [
  {
    section: 'Heavy Weapons',
    name: 'Hand Grenade',
    shortName: 'Hand Grenade',
    skill: 'Athletics',
    expense: 'Incidental',
    radius: '20 m',
    lethality: '15%',
    killRadius: '10 m',
    ammoCapacity: 'N/A',
    description: 'RESTRICTED. Examples: M67, RGO.',
    isRestricted: true,
    sourceType: 'core'
  },
  {
    section: 'Heavy Weapons',
    name: 'Smoke Grenade',
    shortName: 'Smoke Grenade',
    skill: 'Athletics',
    expense: 'Unusual',
    range: '20 m',
    uses: '1',
    radius: '10 m',
    description: 'RESTRICTED. Creates a thick cloud of smoke, providing concealment. All vision-based tests inside or through the smoke are at -40%.',
    isRestricted: true,
    sourceType: 'ai'
  },
  {
    section: 'Heavy Weapons',
    name: 'Rocket-Propelled Grenade Launcher (RPG)',
    shortName: 'RPG Launcher',
    skill: 'Heavy Weapons',
    expense: 'Standard',
    radius: '200 m',
    lethality: '30%',
    killRadius: '10 m',
    ammoCapacity: '1,20',
    description: 'RESTRICTED. Examples: ATK M72 LAW, Bazalt RPG-7V, Bofors AT4 (M136).',
    isRestricted: true,
    sourceType: 'core'
  },
  {
    section: 'Heavy Weapons',
    name: 'Handheld Flamethrower',
    shortName: 'Hand Flamethrower',
    skill: 'Heavy Weapons',
    expense: 'Unusual',
    radius: '5 m',
    lethality: '10%',
    killRadius: '1 m',
    ammoCapacity: '20',
    description: 'Example: Ion XM42.',
    isRestricted: false,
    sourceType: 'core'
  },
  {
    section: 'Heavy Weapons',
    name: 'Military Flamethrower',
    shortName: 'Military Flamethrwr',
    skill: 'Heavy Weapons',
    expense: 'Unusual',
    radius: '10 m',
    lethality: '10%',
    killRadius: '2 m',
    ammoCapacity: '5',
    description: 'RESTRICTED. Example: AEC M9A1-7.',
    isRestricted: true,
    sourceType: 'core'
  },
  {
    section: 'Heavy Weapons',
    name: 'General-Purpose Machine Gun (GPMG)',
    shortName: 'GPMG',
    skill: 'Heavy Weapons',
    expense: 'Major',
    radius: '300 m',
    lethality: '15%',
    killRadius: 'Per burst (page 56)',
    ammoCapacity: '100,3',
    description: 'RESTRICTED. Examples: FN MAG (M240), Kovrov PKM, Saco M60.',
    isRestricted: true,
    sourceType: 'core'
  },
  {
    section: 'Heavy Weapons',
    name: 'Grenade Launcher (GL)',
    shortName: 'Grenade Launcher',
    skill: 'Heavy Weapons',
    expense: 'Major',
    radius: '150 m',
    lethality: '15%',
    killRadius: '10 m',
    ammoCapacity: '1',
    description: 'RESTRICTED. Revolver capacity: 6. Examples: Colt M203, H&K M320, Milkor M32, Springfield M79.',
    isRestricted: true,
    sourceType: 'core'
  },
  {
    section: 'Heavy Weapons',
    name: 'Grenade Machine Gun (GMG)',
    shortName: 'Grenade Machine Gun',
    skill: 'Heavy Weapons',
    expense: 'Major',
    radius: '300 m',
    lethality: '15%*',
    killRadius: '10 m',
    ammoCapacity: '30',
    description: 'RESTRICTED. *If firing a burst (5 grenades), Lethality is 20%. Examples: H&K GMG, Saco MK 19 MOD 3, KBP AGS-17.',
    isRestricted: true,
    sourceType: 'core'
  },
  {
    section: 'Heavy Weapons',
    name: 'Heavy Machine Gun (HMG)',
    shortName: 'HMG',
    skill: 'Heavy Weapons',
    expense: 'Major',
    radius: '400 m',
    lethality: '20%',
    killRadius: 'Per burst (page 56)',
    ammoCapacity: '100,5',
    description: 'RESTRICTED. Examples: Browning M2HB, Degtyaryov DShK, Kovrov NSV.',
    isRestricted: true,
    sourceType: 'core'
  },
  {
    section: 'Heavy Weapons',
    name: 'Light Machine Gun (LMG)',
    shortName: 'LMG',
    skill: 'Heavy Weapons',
    expense: 'Major',
    radius: '200 m',
    lethality: '10%',
    killRadius: 'Per burst (page 56)',
    ammoCapacity: '100 or 200,3',
    description: 'RESTRICTED. Examples: FN MINIMI (M249 SAW), Molot RPK.',
    isRestricted: true,
    sourceType: 'core'
  },
  {
    section: 'Heavy Weapons',
    name: 'Autocannon',
    shortName: 'Autocannon',
    skill: 'Heavy Weapons',
    expense: 'Extreme',
    radius: '400 m',
    lethality: '30%',
    killRadius: '3 m',
    ammoCapacity: '100,5',
    description: 'RESTRICTED. Examples: ATK M242 Bushmaster, KBP 2A70.',
    isRestricted: true,
    sourceType: 'core'
  },
  {
    section: 'Heavy Weapons',
    name: 'Minigun',
    shortName: 'Minigun',
    skill: 'Heavy Weapons',
    expense: 'Extreme',
    radius: '300 m',
    lethality: '20%',
    killRadius: '3 m (long spray only)',
    ammoCapacity: '4000,5',
    description: 'RESTRICTED. Examples: Dillon GAU-17/A, GE M134, KBP GShG-7.62.',
    isRestricted: true,
    sourceType: 'core'
  },
];
