import type { DGItem } from '../types';

export const nonLethalWeapons: DGItem[] = [
  {
    section: 'Tear Gas and Pepper Spray',
    name: 'Pepper Spray Keychain',
    shortName: 'Pepper Spray Keychn',
    skill: 'DEXx5',
    expense: 'Incidental',
    range: '1 m',
    uses: '1',
    radius: '1 target',
    victimsPenalty: '-20% for 1 hr',
    isRestricted: false,
    sourceType: 'core'
  },
  {
    section: 'Tear Gas and Pepper Spray',
    name: 'Pepper Spray Can',
    shortName: 'Pepper Spray Can',
    skill: 'DEXx5',
    expense: 'Incidental',
    range: '3 m',
    uses: '12',
    radius: '2 targets',
    victimsPenalty: '-20% for 1 hr',
    isRestricted: false,
    sourceType: 'core'
  },
  {
    section: 'Tear Gas and Pepper Spray',
    name: 'Tear Gas Grenade (thrown)',
    shortName: 'Tear Gas (thrown)',
    skill: 'Athletics',
    expense: 'Incidental',
    range: '20 m',
    uses: '1',
    radius: '10 m',
    victimsPenalty: '-40% for 1 hr',
    description: "RESTRICTED. Requires special training. Radius halved outdoors. Victim's penalty lasts 1D6 turns.",
    isRestricted: true,
    sourceType: 'core'
  },
  {
    section: 'Tear Gas and Pepper Spray',
    name: 'Tear Gas Grenade (launched)',
    shortName: 'Tear Gas (launched)',
    skill: 'Heavy Weapons',
    expense: 'Incidental',
    range: '50 m',
    uses: '1',
    radius: '10 m',
    victimsPenalty: '-40% for 1 hr',
    description: "RESTRICTED. Requires special training. Radius halved outdoors. Victim's penalty lasts 1D6 turns.",
    isRestricted: true,
    sourceType: 'core'
  },
  {
    section: 'Stun Grenades',
    name: 'Flash-Bang Grenade (thrown)',
    shortName: 'Flash-Bang (thrown)',
    skill: 'Athletics',
    expense: 'Incidental',
    range: '20 m',
    uses: '1',
    radius: '10 m',
    victimsPenalty: '-40%',
    description: "RESTRICTED. Requires special training. Radius halved outdoors. Victim's penalty lasts 1D6 turns.",
    isRestricted: true,
    sourceType: 'core'
  },
  {
    section: 'Stun Grenades',
    name: 'Flash-Bang Grenade (launched)',
    shortName: 'Flash-Bang (launchd)',
    skill: 'Heavy Weapons',
    expense: 'Incidental',
    range: '50 m',
    uses: '1',
    radius: '10 m',
    victimsPenalty: '-40%',
    description: "RESTRICTED. Requires special training. Radius halved outdoors. Victim's penalty lasts 1D6 turns.",
    isRestricted: true,
    sourceType: 'core'
  },
  {
    section: 'Electroshock Weapons',
    name: 'Stun Gun',
    shortName: 'Stun Gun',
    skill: 'DEXx5',
    expense: 'Incidental',
    range: '1 m',
    uses: '10',
    victimsPenalty: '-20% for 1D20 turns',
    isRestricted: false,
    sourceType: 'core'
  },
  {
    section: 'Electroshock Weapons',
    name: 'Shock Baton',
    shortName: 'Shock Baton',
    skill: 'DEXx5',
    expense: 'Incidental',
    range: '1 m',
    uses: '200',
    victimsPenalty: '-20% for 1D20 turns',
    isRestricted: false,
    sourceType: 'core'
  },
  {
    section: 'Electroshock Weapons',
    name: 'CED Pistol',
    shortName: 'CED Pistol',
    skill: 'Firearms',
    expense: 'Standard',
    range: '4 m',
    uses: '4',
    victimsPenalty: '-20% for 1D20 turns',
    description: 'Requires special training.',
    isRestricted: false,
    sourceType: 'core'
  },
];
